import {
  ConnectionSetting,
  DBType,
  RDSBaseDriver,
} from "@l-v-yonsama/multi-platform-database-drivers";
import {
  CancellationTokenSource,
  commands,
  ExtensionContext,
  NotebookCellData,
  NotebookCellKind,
  NotebookData,
  Uri,
  ViewColumn,
  window,
  workspace,
} from "vscode";
import { REFRESH_RESOURCES } from "../constant";
import { CellMeta } from "../types/Notebook";
import { findOpenNotebookDocument } from "../aiTools/lmTools/notebookResolver";
import { showWindowErrorMessage } from "../utilities/alertUtil";
import { flowTransaction } from "../utilities/driverResolver";
import {
  createDirectory,
  deleteResource,
  existsUri,
  writeBytesToResource,
} from "../utilities/fsUtil";
import { log } from "../utilities/logger";
import { StateStorage } from "../utilities/StateStorage";
import { DBNotebookSerializer } from "./serializer";

const PREFIX = "[notebook/sqliteDemo]";

export const SQLITE_DEMO_CONNECTION_NAME = "SQLite Demo";
const DEMO_DIR_NAME = "sqlite-demo";
const DEMO_DB_FILE_NAME = "demo.sqlite";
const DEMO_NOTEBOOK_FILE_NAME = "demo.dbn";
const SHARED_VARIABLE_NAME = "customerSales";

// A small, self-contained customers/products/orders schema, seeded so that
// "sales by customer" produces an interesting (non-uniform) ranking. Customer
// "Rin Kimura" intentionally has no orders, to mirror a realistic "no
// purchases yet" row being naturally excluded by the inner joins below.
const DEMO_SETUP_STATEMENTS: readonly string[] = [
  `CREATE TABLE customers (
    customer_no INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    prefecture TEXT
  )`,
  `CREATE TABLE products (
    product_no INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    unit_price INTEGER NOT NULL
  )`,
  `CREATE TABLE orders (
    order_no INTEGER PRIMARY KEY,
    customer_no INTEGER NOT NULL REFERENCES customers(customer_no),
    order_date TEXT NOT NULL
  )`,
  `CREATE TABLE order_detail (
    order_no INTEGER NOT NULL REFERENCES orders(order_no),
    detail_no INTEGER NOT NULL,
    product_no INTEGER NOT NULL REFERENCES products(product_no),
    quantity INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    PRIMARY KEY (order_no, detail_no)
  )`,
  `INSERT INTO customers (customer_no, name, prefecture) VALUES
    (1, 'Taro Yamada', 'Tokyo'),
    (2, 'Hanako Suzuki', 'Osaka'),
    (3, 'Ichiro Tanaka', 'Aichi'),
    (4, 'Yuki Sato', 'Fukuoka'),
    (5, 'Kenji Watanabe', 'Hokkaido'),
    (6, 'Aoi Ito', 'Tokyo'),
    (7, 'Sora Kobayashi', 'Kyoto'),
    (8, 'Rin Kimura', 'Okinawa')`,
  `INSERT INTO products (product_no, name, unit_price) VALUES
    (1, 'Notebook PC', 98000),
    (2, 'Wireless Mouse', 2500),
    (3, 'Mechanical Keyboard', 12000),
    (4, 'USB-C Hub', 4500),
    (5, 'External SSD 1TB', 15000),
    (6, 'Webcam', 6000)`,
  `INSERT INTO orders (order_no, customer_no, order_date) VALUES
    (1, 1, '2026-01-05'),
    (2, 2, '2026-01-10'),
    (3, 1, '2026-02-02'),
    (4, 3, '2026-02-14'),
    (5, 4, '2026-02-20'),
    (6, 5, '2026-03-01'),
    (7, 2, '2026-03-05'),
    (8, 6, '2026-03-11'),
    (9, 7, '2026-03-15'),
    (10, 1, '2026-03-20')`,
  `INSERT INTO order_detail (order_no, detail_no, product_no, quantity, amount) VALUES
    (1, 1, 1, 1, 98000),
    (1, 2, 2, 2, 5000),
    (2, 1, 3, 1, 12000),
    (3, 1, 5, 1, 15000),
    (3, 2, 4, 1, 4500),
    (4, 1, 2, 1, 2500),
    (4, 2, 6, 1, 6000),
    (5, 1, 1, 1, 98000),
    (6, 1, 3, 2, 24000),
    (7, 1, 5, 1, 15000),
    (8, 1, 4, 3, 13500),
    (9, 1, 2, 4, 10000),
    (10, 1, 6, 1, 6000)`,
];

const SALES_BY_CUSTOMER_SQL = `SELECT c.name AS customer_name, SUM(d.amount) AS total_amount
FROM customers c
JOIN orders o ON o.customer_no = c.customer_no
JOIN order_detail d ON d.order_no = o.order_no
GROUP BY c.customer_no, c.name
ORDER BY total_amount DESC`;

function buildDemoNotebookCells(connectionName: string): NotebookCellData[] {
  const introCell = new NotebookCellData(
    NotebookCellKind.Markup,
    [
      "# SQLite Demo",
      "",
      "This notebook was generated by **Create SQLite Demo**. It runs entirely against a local",
      "SQLite file (`demo.sqlite`) created next to this notebook — no external database is required.",
      "",
      'Feel free to edit or delete `demo.sqlite`, `demo.dbn`, and the "SQLite Demo" connection at any',
      "time; nothing else in Database Notebook depends on them.",
      "",
      "Use **Run All** (▶▶ in the toolbar above) to run this notebook top to bottom. The TypeScript",
      "cell needs the SQL cell's result from that same run: each individual \"run cell\" click starts",
      "its own isolated session, so running cells one at a time — even in the right order — will not",
      "carry the SQL cell's result over to it.",
    ].join("\n"),
    "markdown"
  );

  const salesSqlCell = new NotebookCellData(NotebookCellKind.Code, SALES_BY_CUSTOMER_SQL, "sql");
  const salesSqlMeta: CellMeta = {
    connectionName,
    savingSharedVariables: true,
    sharedVariableName: SHARED_VARIABLE_NAME,
  };
  salesSqlCell.metadata = salesSqlMeta;

  const tsCell = new NotebookCellData(
    NotebookCellKind.Code,
    [
      "// This cell reads the SQL cell's result above via the shared variable below. That only",
      "// works if the SQL cell ran in the SAME execution as this cell (e.g. via \"Run All\"): each",
      "// individual \"run cell\" click starts a fresh, isolated session, so the SQL cell's result",
      "// from an earlier run -- even a moment ago -- is not visible here.",
      "//",
      "// `variables.get()` is generic: parameterize it with `SavedCellResult<...>` (an ambient",
      "// type matching what a SQL cell saves) to get real completions below -- metadata.rdh,",
      "// metadata.rdh.rows, etc.",
      `const { success, metadata } = variables.get<SavedCellResult<{ rdh: ResultSetData }>>(`,
      `  "${SHARED_VARIABLE_NAME}",`,
      "  { success: false }",
      ");",
      "",
      "if (success && metadata) {",
      "  const rows = metadata.rdh.rows.map((row) => row.values);",
      '  const top = rows[0];',
      '  const total = rows.reduce((sum, row) => sum + Number(row["total_amount"]), 0);',
      '  console.log(`Top customer: ${top["customer_name"]} (${top["total_amount"]})`);',
      "  console.log(`Total sales across ${rows.length} customers: ${total}`);",
      "} else {",
      "  console.log(",
      '    \'No result yet from this run. Use "Run All" at the top of the notebook -- running cells one at a time does not share results between them.\'',
      "  );",
      "}",
    ].join("\n"),
    "typescript"
  );

  const chartSqlCell = new NotebookCellData(
    NotebookCellKind.Code,
    SALES_BY_CUSTOMER_SQL,
    "sql"
  );
  const chartSqlMeta: CellMeta = {
    connectionName,
    chart: {
      title: "Sales by customer",
      type: "bar",
      multipleDataset: false,
      showDataLabels: true,
      showTitle: true,
      label: "customer_name",
      data: "total_amount",
      dataX: "",
      dataY: "",
    },
  };
  chartSqlCell.metadata = chartSqlMeta;

  const findingsCell = new NotebookCellData(
    NotebookCellKind.Markup,
    [
      "## Findings",
      "",
      "_Fill in what you found here._ The SQL cell above lists total sales per customer; the",
      "TypeScript cell computed the top customer and the overall total from that same result via",
      `the shared variable \`${SHARED_VARIABLE_NAME}\`.`,
    ].join("\n"),
    "markdown"
  );

  const exportCell = new NotebookCellData(
    NotebookCellKind.Markup,
    [
      "## Exporting results",
      "",
      "Open the result panel for any SQL cell above and use the toolbar buttons to take the data",
      "with you:",
      "",
      "- $(file-lines) **Output as HTML**",
      "- $(file-excel) **Output as Excel**",
      "",
      "Both prompt you to choose where to save the file.",
    ].join("\n"),
    "markdown"
  );

  return [introCell, salesSqlCell, tsCell, chartSqlCell, findingsCell, exportCell];
}

type DemoLocation = {
  demoDirUri: Uri;
  dbUri: Uri;
  notebookUri: Uri;
};

function resolveDemoLocation(context: ExtensionContext): DemoLocation {
  const demoDirUri = Uri.joinPath(context.globalStorageUri, DEMO_DIR_NAME);
  return {
    demoDirUri,
    dbUri: Uri.joinPath(demoDirUri, DEMO_DB_FILE_NAME),
    notebookUri: Uri.joinPath(demoDirUri, DEMO_NOTEBOOK_FILE_NAME),
  };
}

/**
 * Options threaded through from the command invocation. `openBeside` is set only when the
 * walkthrough's command link passes `{"openBeside": true}` as an argument (see
 * package.json's `dbNotebookGettingStarted` walkthrough) -- from the Command Palette or
 * "Create a new file" menu, the notebook opens in the active editor group as usual.
 */
export type SqliteDemoOptions = {
  openBeside?: boolean;
};

async function openNotebook(uri: Uri, options?: SqliteDemoOptions): Promise<void> {
  const document = await workspace.openNotebookDocument(uri);
  await window.showNotebookDocument(
    document,
    options?.openBeside ? { viewColumn: ViewColumn.Beside } : undefined
  );
}

/**
 * (Re)builds `demo.sqlite` + `demo.dbn` at the given location and opens the notebook.
 * Callers are responsible for clearing out any previous files first -- this always
 * creates from scratch and errors out on an existing demo.sqlite (see `createSqliteDemo`'s
 * own leftover-file cleanup for the one case that's expected and handled here as well).
 */
async function buildAndOpenSqliteDemo(
  stateStorage: StateStorage,
  { demoDirUri, dbUri, notebookUri }: DemoLocation,
  options?: SqliteDemoOptions
): Promise<void> {
  const setting: ConnectionSetting = {
    dbType: DBType.SQLite,
    name: SQLITE_DEMO_CONNECTION_NAME,
    database: dbUri.fsPath,
    environment: "local",
    comment: 'Created by "Create SQLite Demo". Safe to delete.',
  };

  // A stale demo.sqlite (e.g. left over from a previous, interrupted run) would make the
  // DDL below fail with "table already exists". It's disposable seed data, so clear it.
  if (await existsUri(dbUri)) {
    await deleteResource(dbUri);
  }

  const setupResult = await flowTransaction<RDSBaseDriver, void>(
    setting,
    async (driver) => {
      for (const stmt of DEMO_SETUP_STATEMENTS) {
        await driver.requestSql({ sql: stmt });
      }
    },
    { transactionControlType: "alwaysCommit" },
    false
  );

  if (!setupResult.ok) {
    showWindowErrorMessage(`Failed to create the SQLite demo database: ${setupResult.message}`);
    return;
  }

  const existingSetting = await stateStorage.getConnectionSettingByName(SQLITE_DEMO_CONNECTION_NAME);
  if (!existingSetting) {
    await stateStorage.addConnectionSetting(setting);
    await commands.executeCommand(REFRESH_RESOURCES);
  }

  const notebookData = new NotebookData(buildDemoNotebookCells(SQLITE_DEMO_CONNECTION_NAME));
  const tokenSource = new CancellationTokenSource();
  try {
    const bytes = await new DBNotebookSerializer().serializeNotebook(
      notebookData,
      tokenSource.token
    );
    await writeBytesToResource(notebookUri, bytes);
  } finally {
    tokenSource.dispose();
  }

  log(`${PREFIX} created SQLite demo at [${demoDirUri.fsPath}]`);
  await openNotebook(notebookUri, options);
}

/**
 * Creates (or, if already present, simply reopens) a small local SQLite demo:
 * a seeded `demo.sqlite`, a `SQLite Demo` connection setting pointing at it,
 * and a `demo.dbn` walking through SQL → TypeScript → chart → Markdown. Every
 * artifact lives under the extension's own global storage — nothing is
 * written into the user's workspace.
 */
export async function createSqliteDemo(
  context: ExtensionContext,
  stateStorage: StateStorage,
  options?: SqliteDemoOptions
): Promise<void> {
  const location = resolveDemoLocation(context);
  await createDirectory(location.demoDirUri);

  if (await existsUri(location.notebookUri)) {
    log(`${PREFIX} demo notebook already exists, reopening [${location.notebookUri.fsPath}]`);
    await openNotebook(location.notebookUri, options);
    return;
  }

  await buildAndOpenSqliteDemo(stateStorage, location, options);
}

/**
 * Deletes the existing `demo.sqlite`/`demo.dbn` and rebuilds them from scratch. Used to
 * recover from a demo the user has edited into an unrecognizable state, and doubles as the
 * way to re-test `createSqliteDemo`'s first-run path during development, since the demo
 * lives outside the workspace (under global storage) and isn't reachable from the Explorer.
 */
export async function resetSqliteDemo(
  context: ExtensionContext,
  stateStorage: StateStorage,
  options?: SqliteDemoOptions
): Promise<void> {
  const location = resolveDemoLocation(context);
  await createDirectory(location.demoDirUri);

  if (findOpenNotebookDocument(location.notebookUri)) {
    showWindowErrorMessage(
      'Close the open "demo.dbn" tab first, then run "Reset SQLite Demo" again.'
    );
    return;
  }

  if (await existsUri(location.notebookUri)) {
    await deleteResource(location.notebookUri);
  }

  await buildAndOpenSqliteDemo(stateStorage, location, options);
}
