export type ComponentName =
  | "MdhView"
  | "DiffMdhView"
  | "ScanPanel"
  | "VariablesPanel"
  | "CsvParseSettingPanel"
  | "CreateInsertScriptSettingsPanel"
  | "HarFilePanel"
  | "HttpEventPanel"
  | "ViewConditionPanel"
  | "WriteToClipboardParamsPanel"
  | "WriteHttpEventToClipboardParamsPanel"
  | "DBFormView"
  | "ERDiagramSettingsPanel"
  | "RecordRuleEditor"
  | "NotebookCellMetadataPanel"
  | "CodeResolverEditor";
