import {
  DbDynamoTable,
  DbDynamoTableColumn,
} from "@l-v-yonsama/multi-platform-database-drivers";
import { describe, expect, it } from "vitest";
import { restoreDynamoQueryPanelState } from "../../src/utilities/dynamoDbQueryPanelHistory";

const buildTable = (): DbDynamoTable => {
  const table = new DbDynamoTable("orders", {
    lsi: [
      {
        IndexName: "lsiStatus",
        KeySchema: [
          { AttributeName: "tenantId", KeyType: "HASH" },
          { AttributeName: "status", KeyType: "RANGE" },
        ],
        Projection: { ProjectionType: "ALL" },
      },
    ],
    gsi: [
      {
        IndexName: "gsiCountry",
        KeySchema: [
          { AttributeName: "country", KeyType: "HASH" },
          { AttributeName: "orderId", KeyType: "RANGE" },
        ],
        Projection: { ProjectionType: "ALL" },
      },
    ],
  } as never);
  table.addChild(new DbDynamoTableColumn("tenantId", "S", true, false));
  table.addChild(new DbDynamoTableColumn("orderId", "S", false, true));
  table.addChild(new DbDynamoTableColumn("status", "S", false, false));
  table.addChild(new DbDynamoTableColumn("amount", "N", false, false));
  table.addChild(new DbDynamoTableColumn("country", "S", false, false));
  return table;
};

describe("restoreDynamoQueryPanelState", () => {
  it("restores all editable Query Panel fields from its saved native Query input", () => {
    const restored = restoreDynamoQueryPanelState(
      {
        TableName: "orders",
        IndexName: "lsiStatus",
        Limit: 25,
        ScanIndexForward: false,
        ConsistentRead: true,
        KeyConditionExpression: "#pk = :pk AND #sk BETWEEN :sk1 AND :sk2",
        FilterExpression:
          "#f0_amount >= :f0_amount AND contains(#f1_status, :f1_status) AND #f2_orderId BETWEEN :F2orderId1 AND :F2orderId2",
        ProjectionExpression: "#p0, #p1",
        ExpressionAttributeNames: {
          "#pk": "tenantId",
          "#sk": "status",
          "#f0_amount": "amount",
          "#f1_status": "status",
          "#f2_orderId": "orderId",
          "#p0": "tenantId",
          "#p1": "amount",
        },
        ExpressionAttributeValues: {
          ":pk": { S: "T#001" },
          ":sk1": { S: "PENDING" },
          ":sk2": { S: "SHIPPED" },
          ":f0_amount": { N: "100" },
          ":f1_status": { S: "END" },
          ":F2orderId1": { S: "O#010" },
          ":F2orderId2": { S: "O#020" },
        },
      },
      buildTable()
    );

    expect(restored).toEqual({
      target: "$lsi:lsiStatus",
      limit: 25,
      pkValue: "T#001",
      skValue: "PENDING, SHIPPED",
      skOpe: "between",
      sortDesc: true,
      filters: [
        { name: "amount", operator: "greaterThanInclusive", value: "100" },
        { name: "status", operator: "contains", value: "END" },
        { name: "orderId", operator: "between", value: "O#010, O#020" },
      ],
      projectionMode: "specific",
      projectedAttributes: ["tenantId", "amount"],
      consistentRead: true,
    });
  });

  it("restores a GSI, begins_with sort key, default projection and eventual read", () => {
    expect(
      restoreDynamoQueryPanelState(
        {
          TableName: "orders",
          IndexName: "gsiCountry",
          KeyConditionExpression: "#pk = :pk AND begins_with(#sk, :sk)",
          ExpressionAttributeNames: { "#pk": "country", "#sk": "orderId" },
          ExpressionAttributeValues: { ":pk": { S: "JP" }, ":sk": { S: "O#" } },
        },
        buildTable()
      )
    ).toMatchObject({
      target: "$gsi:gsiCountry",
      pkValue: "JP",
      skValue: "O#",
      skOpe: "beginsWith",
      projectionMode: "default",
      projectedAttributes: [],
      consistentRead: false,
    });
  });

  it("restores ALL_ATTRIBUTES as the LSI all-table-attributes mode", () => {
    expect(
      restoreDynamoQueryPanelState(
        {
          TableName: "orders",
          IndexName: "lsiStatus",
          Select: "ALL_ATTRIBUTES",
          KeyConditionExpression: "#pk = :pk",
          ExpressionAttributeNames: { "#pk": "tenantId" },
          ExpressionAttributeValues: { ":pk": { S: "T#001" } },
        },
        buildTable()
      ).projectionMode
    ).toBe("allTableAttributes");
  });

  it("rejects an input whose index no longer exists instead of silently changing the target", () => {
    expect(() =>
      restoreDynamoQueryPanelState(
        {
          TableName: "orders",
          IndexName: "deletedIndex",
          KeyConditionExpression: "#pk = :pk",
          ExpressionAttributeValues: { ":pk": { S: "T#001" } },
        },
        buildTable()
      )
    ).toThrow("index 'deletedIndex' no longer exists");
  });

  it("rejects expressions not generated by DynamoDB Query Panel", () => {
    expect(() =>
      restoreDynamoQueryPanelState(
        {
          TableName: "orders",
          KeyConditionExpression: "tenantId = :tenant",
          ExpressionAttributeValues: { ":tenant": { S: "T#001" } },
        },
        buildTable()
      )
    ).toThrow("not in the format generated by DynamoDB Query Panel");
  });
});
