import type {
  DbDynamoTable,
  QueryItemsAtClientInputParams,
} from "@l-v-yonsama/multi-platform-database-drivers";
import type {
  DynamoQueryFilter,
  DynamoQueryProjectionMode,
} from "../../shared/DynamoDBConditionParams";

export type RestoredDynamoQueryPanelState = {
  target: string;
  limit?: number;
  pkValue: string;
  skValue: string;
  skOpe: string;
  sortDesc: boolean;
  filters: DynamoQueryFilter[];
  projectionMode: DynamoQueryProjectionMode;
  projectedAttributes: string[];
  consistentRead: boolean;
};

const fail = (detail: string): never => {
  throw new Error(`The saved DynamoDB Query history cannot be restored: ${detail}`);
};

const resolveTarget = (
  input: QueryItemsAtClientInputParams,
  tableRes: Pick<DbDynamoTable, "name" | "attr">
): string => {
  if (input.TableName !== tableRes.name) {
    return fail(`table '${input.TableName ?? ""}' does not match '${tableRes.name}'.`);
  }
  if (!input.IndexName) {
    return "$table";
  }
  if (tableRes.attr.lsi.some((index) => index.IndexName === input.IndexName)) {
    return `$lsi:${input.IndexName}`;
  }
  if (tableRes.attr.gsi.some((index) => index.IndexName === input.IndexName)) {
    return `$gsi:${input.IndexName}`;
  }
  return fail(`index '${input.IndexName}' no longer exists on table '${tableRes.name}'.`);
};

const valueToText = (attributeValue: unknown): string => {
  if (!attributeValue || typeof attributeValue !== "object") {
    return fail("an expression attribute value is missing or invalid.");
  }
  const entries = Object.entries(attributeValue as Record<string, unknown>);
  if (entries.length !== 1) {
    return fail("an expression attribute value does not contain exactly one DynamoDB type.");
  }
  const [type, value] = entries[0];
  if (type === "NULL") {
    return "";
  }
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value instanceof Uint8Array) {
    return Buffer.from(value).toString("base64");
  }
  if (Array.isArray(value)) {
    return value.map(String).join(", ");
  }
  if (
    type === "B" &&
    value &&
    typeof value === "object" &&
    (value as { type?: unknown }).type === "Buffer" &&
    Array.isArray((value as { data?: unknown }).data)
  ) {
    return Buffer.from((value as { data: number[] }).data).toString("base64");
  }
  return fail(`the ${type} expression attribute value cannot be represented in the Query Panel.`);
};

const getValue = (
  values: QueryItemsAtClientInputParams["ExpressionAttributeValues"],
  token: string
): string => {
  const value = values?.[token];
  if (value === undefined) {
    return fail(`expression attribute value '${token}' is missing.`);
  }
  return valueToText(value);
};

const restoreKeyCondition = (
  input: QueryItemsAtClientInputParams
): Pick<RestoredDynamoQueryPanelState, "pkValue" | "skValue" | "skOpe"> => {
  const expression = input.KeyConditionExpression?.trim();
  const values = input.ExpressionAttributeValues;
  if (!expression) {
    return fail("KeyConditionExpression is missing.");
  }
  const match = expression.match(/^#pk\s*=\s*:pk(?:\s+AND\s+(.+))?$/);
  if (!match) {
    return fail("KeyConditionExpression is not in the format generated by DynamoDB Query Panel.");
  }

  const pkValue = getValue(values, ":pk");
  const sortCondition = match[1]?.trim();
  if (!sortCondition) {
    return { pkValue, skValue: "", skOpe: "" };
  }

  const binary = sortCondition.match(/^#sk\s*(=|<=|<|>=|>)\s*:sk$/);
  if (binary) {
    const operatorBySymbol: Record<string, string> = {
      "=": "equal",
      "<": "lessThan",
      "<=": "lessThanInclusive",
      ">": "greaterThan",
      ">=": "greaterThanInclusive",
    };
    return {
      pkValue,
      skValue: getValue(values, ":sk"),
      skOpe: operatorBySymbol[binary[1]],
    };
  }
  if (/^#sk\s+BETWEEN\s+:sk1\s+AND\s+:sk2$/i.test(sortCondition)) {
    return {
      pkValue,
      skValue: `${getValue(values, ":sk1")}, ${getValue(values, ":sk2")}`,
      skOpe: "between",
    };
  }
  if (/^begins_with\(\s*#sk\s*,\s*:sk\s*\)$/i.test(sortCondition)) {
    return { pkValue, skValue: getValue(values, ":sk"), skOpe: "beginsWith" };
  }
  return fail("the sort-key condition is not in a format generated by DynamoDB Query Panel.");
};

const restoreFilters = (input: QueryItemsAtClientInputParams): DynamoQueryFilter[] => {
  const expression = input.FilterExpression?.trim();
  if (!expression) {
    return [];
  }
  const names = input.ExpressionAttributeNames ?? {};
  const values = input.ExpressionAttributeValues;
  const token = "[:#][A-Za-z0-9_]+";
  const filterPattern = new RegExp(
    `(?:` +
      `(begins_with|contains)\\(\\s*(${token})\\s*,\\s*(${token})\\s*\\)` +
      `|(${token})\\s+BETWEEN\\s+(${token})\\s+AND\\s+(${token})` +
      `|(${token})\\s*(<=|>=|=|<|>)\\s*(${token})` +
      `)`,
    "gi"
  );
  const filters: DynamoQueryFilter[] = [];
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = filterPattern.exec(expression)) !== null) {
    const separator = expression.slice(cursor, match.index).trim();
    if ((cursor === 0 && separator !== "") || (cursor > 0 && separator.toUpperCase() !== "AND")) {
      return fail("FilterExpression contains an unsupported expression.");
    }

    let nameToken: string;
    let operator: string;
    let value: string;
    if (match[1]) {
      operator = match[1].toLowerCase() === "contains" ? "contains" : "beginsWith";
      nameToken = match[2];
      value = getValue(values, match[3]);
    } else if (match[4]) {
      operator = "between";
      nameToken = match[4];
      value = `${getValue(values, match[5])}, ${getValue(values, match[6])}`;
    } else {
      const operatorBySymbol: Record<string, string> = {
        "=": "equal",
        "<": "lessThan",
        "<=": "lessThanInclusive",
        ">": "greaterThan",
        ">=": "greaterThanInclusive",
      };
      nameToken = match[7];
      operator = operatorBySymbol[match[8]];
      value = getValue(values, match[9]);
    }
    const name = names[nameToken];
    if (!name) {
      return fail(`expression attribute name '${nameToken}' is missing.`);
    }
    filters.push({ name, operator, value });
    cursor = filterPattern.lastIndex;
  }

  if (filters.length === 0 || expression.slice(cursor).trim() !== "") {
    return fail("FilterExpression contains an unsupported expression.");
  }
  return filters;
};

const restoreProjection = (
  input: QueryItemsAtClientInputParams
): Pick<RestoredDynamoQueryPanelState, "projectionMode" | "projectedAttributes"> => {
  if (input.Select === "ALL_ATTRIBUTES") {
    return { projectionMode: "allTableAttributes", projectedAttributes: [] };
  }
  if (!input.ProjectionExpression?.trim()) {
    return { projectionMode: "default", projectedAttributes: [] };
  }
  const names = input.ExpressionAttributeNames ?? {};
  const projectedAttributes = input.ProjectionExpression.split(",").map((part) => {
    const token = part.trim();
    const name = names[token];
    if (!name) {
      return fail(`ProjectionExpression name '${token}' is missing.`);
    }
    return name;
  });
  return { projectionMode: "specific", projectedAttributes };
};

// Converts only requests produced by DynamoDB Query Panel. Query History stores
// the exact native QueryCommandInput for re-execution; this function is the
// inverse of DynamoQueryPanel.resetByTarget(), making that input editable
// again without persisting a second, potentially divergent UI-state object.
export const restoreDynamoQueryPanelState = (
  input: QueryItemsAtClientInputParams,
  tableRes: Pick<DbDynamoTable, "name" | "attr">
): RestoredDynamoQueryPanelState => ({
  target: resolveTarget(input, tableRes),
  ...(typeof input.Limit === "number" && input.Limit > 0 ? { limit: input.Limit } : {}),
  ...restoreKeyCondition(input),
  sortDesc: input.ScanIndexForward === false,
  filters: restoreFilters(input),
  ...restoreProjection(input),
  consistentRead: input.ConsistentRead === true,
});
